export const animeEndpoints = {
  fullById: "/anime/{id}/full",
  byId: "/anime/{id}",
  characters: "/anime/{id}/characters",
  staff: "/anime/{id}/staff",
  episodes: "/anime/{id}/episodes",
  episodeById: "/anime/{id}/episodes/{episode}",
  news: "/anime/{id}/news",
  forum: "/anime/{id}/forum",
  videos: "/anime/{id}/videos",
  videoEpisodes: "/anime/{id}/videos/episodes",
  pictures: "/anime/{id}/pictures",
  statistics: "/anime/{id}/statistics",
  moreInfo: "/anime/{id}/moreinfo",
  recommendations: "/anime/{id}/recommendations",
  userUpdates: "/anime/{id}/userupdates",
  reviews: "/anime/{id}/reviews",
  relations: "/anime/{id}/relations",
  themes: "/anime/{id}/themes",
  external: "/anime/{id}/external",
  streaming: "/anime/{id}/streaming",
  search: "/anime",
} as const;
