export const mangaEndpoints = {
  fullById: "/manga/{id}/full",
  byId: "/manga/{id}",
  characters: "/manga/{id}/characters",
  news: "/manga/{id}/news",
  topics: "/manga/{id}/forum",
  pictures: "/manga/{id}/pictures",
  statistics: "/manga/{id}/statistics",
  moreInfo: "/manga/{id}/moreinfo",
  recommendations: "/manga/{id}/recommendations",
  userUpdates: "/manga/{id}/userupdates",
  reviews: "/manga/{id}/reviews",
  relations: "/manga/{id}/relations",
  external: "/manga/{id}/external",
  search: "/manga",
} as const;
